### ISSUE TITLE
Git Push fails on new version

### ISSUE THREAD

**Issue by ocdtrekkie** [cem/gogs-sandstorm#17]
"remote: Gogs: Internal error" and "pre-receive hook declined" come up when you try and `git push`.

I looked in my grain's pre-receive.log and found this:

`2018/03/14 03:08:40 [FATAL] [...its/gogs/cmd/serv.go:88 setup()] SetEngine: Fail to connect to database: Fail to create directories: mkdir data: read-only file system`

Kenton has unpublished the package since this is a significant breakage issue.

**Comment by kentonv** [comment]
I just want to say, though, that I'm so happy you posted an update! :D

**Comment by cem** [comment]
Ah, sorry about this. *Of course* I forget to test the most important function of the app.

I've published v0.11.34-fix1 which should fix this.

**Comment by ocdtrekkie** [comment]
@cem TimMc says it is not fixed. (I have not tested it yet, personally. Couple hours for that.)

Also, not an issue that I'd block approval on, but your contactEmail metadata does not resolve (domain seems to not exist), so I can't message you when things are approved/rejected/unapproved/etc.

**Comment by ocdtrekkie** [comment]
TimMc forgot to push one of the buttons, it may be fine.

EDIT: Yeah, it works, he says. Sorry to raise panic. ;)

**Comment by ocdtrekkie** [comment]
Checked my git push and approved.
